/* MTI_DPI */

/*
 * Copyright 2002-2012 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
main_call_from_sv(
    int arg,
    const char* argv);

DPI_LINK_DECL int
dpi_clock(
    int mode,
    int64_t cycle);

DPI_LINK_DECL int
dpi_delay(
    int64_t cycle);

#endif 
